openapi: 3.0.3
info:
  title: _well_known API
  description: okta _well_known API
  version: 5.1.0
paths:
  /.well-known/app-authenticator-configuration:
    get:
      x-okta-lifecycle:
        lifecycle: GA
        isGenerallyAvailable: false
        SKUs: []
      summary: Retrieve the well-known app authenticator configuration
      description: >-
        Retrieves the well-known app authenticator configuration. Includes an
        app authenticator's settings, supported methods, and other details.
      operationId: getWellKnownAppAuthenticatorConfiguration
      parameters:
        - name: oauthClientId
          in: query
          description: Filters app authenticator configurations by `oauthClientId`
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/WellKnownAppAuthenticatorConfiguration'
              examples:
                AuthenticatorConfiguration:
                  $ref: >-
                    #/components/examples/WellKnownAppAuthenticatorConfigurationCustomApp
        '400':
          $ref: '#/components/responses/ErrorMissingRequiredParameter400'
        '429':
          $ref: '#/components/responses/ErrorTooManyRequests429'
      security: []
      tags:
        - Authenticator
  /.well-known/apple-app-site-association:
    get:
      summary: Retrieve the customized apple-app-site-association URI content
      description: >-
        Retrieves the content of the `apple-app-site-assocation` well-known URI


        > **Note:**  When serving this URI, Okta adds `authsrv` content to
        provide a seamless experience for Okta Verify. You can't modify the
        content in the `authsrv` object.
      operationId: getAppleAppSiteAssociationWellKnownURI
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PublicAppleAppSiteWellKnownURI'
              examples:
                Response:
                  $ref: '#/components/examples/PublicAppleAppSiteWellKnownURIResponse'
        '429':
          $ref: '#/components/responses/ErrorTooManyRequests429'
      security: []
      tags:
        - AssociatedDomainCustomizations
    x-okta-lifecycle:
      lifecycle: EA
      isGenerallyAvailable: false
      SKUs:
        - Okta Identity Engine
  /.well-known/assetlinks.json:
    get:
      summary: Retrieve the customized assetlinks.json URI content
      description: Retrieves the content of the `assetlinks.json` well-known URI
      operationId: getAssetLinksWellKnownURI
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PublicAssetLinksWellKnownURI'
              examples:
                Response:
                  $ref: '#/components/examples/PublicAssetLinksWellKnownURIResponse'
        '404':
          $ref: '#/components/responses/ErrorResourceNotFound404'
        '429':
          $ref: '#/components/responses/ErrorTooManyRequests429'
      security: []
      tags:
        - AssociatedDomainCustomizations
    x-okta-lifecycle:
      lifecycle: EA
      isGenerallyAvailable: false
      SKUs:
        - Okta Identity Engine
  /.well-known/okta-organization:
    get:
      summary: Retrieve the Org metadata
      description: >-
        Retrieves the org metadata, which includes the org ID, configured custom
        domains, and authentication pipeline
      operationId: getWellknownOrgMetadata
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WellKnownOrgMetadata'
              examples:
                Identity Engine org with a custom domain:
                  $ref: >-
                    #/components/examples/WellKnownOrgMetadataResponseCustomUrlOie
                Classic Engine org:
                  $ref: '#/components/examples/WellKnownOrgMetadataResponseClassic'
        '429':
          $ref: '#/components/responses/ErrorTooManyRequests429'
      security: []
      tags:
        - OrgSettingMetadata
      x-okta-lifecycle:
        isCorsEnabled: true
        lifecycle: GA
        isGenerallyAvailable: true
  /.well-known/ssf-configuration:
    get:
      summary: Retrieve the SSF transmitter metadata
      description: >-
        Retrieves SSF Transmitter configuration metadata. This includes all
        supported endpoints and key information about certain properties of the
        Okta org as the transmitter, such as `delivery_methods_supported`,
        `issuer`, and `jwks_uri`.
      operationId: getWellknownSsfMetadata
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WellKnownSSFMetadata'
              examples:
                wellKnownSSFMetadataExample:
                  $ref: '#/components/examples/wellKnownSSFMetadataExample'
        '401':
          $ref: '#/components/responses/ErrorInvalidToken401'
        '403':
          $ref: '#/components/responses/ErrorAccessDenied403'
        '404':
          $ref: '#/components/responses/ErrorResourceNotFound404'
        '429':
          $ref: '#/components/responses/ErrorTooManyRequests429'
      security: []
      tags:
        - SSFTransmitter
      x-okta-lifecycle:
        lifecycle: LIMITED_GA
        isGenerallyAvailable: false
        SKUs:
          - Okta Identity Engine
  /.well-known/webauthn:
    get:
      summary: Retrieve the customized webauthn URI content
      description: Retrieves the content of the `webauthn` well-known URI
      operationId: getWebAuthnWellKnownURI
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PublicWebauthnSiteWellKnownURI'
              examples:
                Response:
                  $ref: '#/components/examples/PublicWebauthnWellKnownURIResponse'
        '404':
          $ref: '#/components/responses/ErrorResourceNotFound404'
        '429':
          $ref: '#/components/responses/ErrorTooManyRequests429'
      security: []
      tags:
        - AssociatedDomainCustomizations
    x-okta-lifecycle:
      lifecycle: EA
      isGenerallyAvailable: false
      SKUs:
        - Okta Identity Engine
components:
  schemas:
    WellKnownAppAuthenticatorConfiguration:
      type: object
      properties:
        appAuthenticatorEnrollEndpoint:
          type: string
          description: The authenticator enrollment endpoint
        authenticatorId:
          type: string
          description: The unique identifier of the app authenticator
        createdDate:
          type: string
          description: Timestamp when the authenticator was created
          format: date-time
        key:
          $ref: '#/components/schemas/AuthenticatorKeyEnum'
        lastUpdated:
          type: string
          description: Timestamp when the authenticator was last modified
          format: date-time
        name:
          type: string
          description: The authenticator display name
        orgId:
          type: string
          description: The `id` of the Okta Org
        settings:
          type: object
          properties:
            userVerification:
              $ref: '#/components/schemas/CustomAppUserVerificationEnum'
        supportedMethods:
          type: array
          items:
            $ref: '#/components/schemas/SupportedMethods'
        type:
          type: string
          description: The type of authenticator
          enum:
            - app
    PublicAppleAppSiteWellKnownURI:
      description: The well-known URI content in JSON object format
      type: object
    PublicAssetLinksWellKnownURI:
      description: The well-known URI content in a JSON array of objects format
      type: array
      properties:
        items:
          type: object
    WellKnownOrgMetadata:
      type: object
      properties:
        id:
          type: string
          description: Org unique identifier
        pipeline:
          $ref: '#/components/schemas/PipelineType'
        _links:
          type: object
          description: >-
            Specifies link relations (see [Web
            Linking](https://www.rfc-editor.org/rfc/rfc8288)) available for this
            object using the [JSON Hypertext Application
            Language](https://datatracker.ietf.org/doc/html/draft-kelly-json-hal-06)
            specification
          readOnly: true
          properties:
            alternate:
              allOf:
                - $ref: '#/components/schemas/HrefObject'
                - description: Link to the custom domain org URL
            organization:
              allOf:
                - $ref: '#/components/schemas/HrefObject'
                - description: Link to the org URL
    WellKnownSSFMetadata:
      title: Shared Signals Framework Metadata
      description: >-
        Metadata about Okta as a transmitter and relevant information for
        configuration.
      type: object
      properties:
        authorization_schemes:
          type: array
          description: >-
            An array of JSON objects that specify the authorization scheme
            properties supported by the transmitter
          items:
            $ref: '#/components/schemas/WellKnownSSFMetadataSpecUrn'
        configuration_endpoint:
          type: string
          format: uri
          description: The URL of the SSF Stream configuration endpoint
          example: https://{yourOktaDomain}/api/v1/ssf/stream
        default_subjects:
          type: string
          description: >-
            A string that indicates the default behavior of newly created
            streams
          enum:
            - ALL
            - NONE
          x-enumDescriptions:
            ALL: >-
              Indicates that any subjects that are appropriate for the stream
              are added to the stream by default.
            NONE: Indicates that no subjects are added by default
        delivery_methods_supported:
          type: array
          items:
            type: string
            format: uri
          description: An array of supported SET delivery methods
          example:
            - https://schemas.openid.net/secevent/risc/delivery-method/push
            - urn:ietf:rfc:8935
        issuer:
          type: string
          description: >-
            The issuer used in Security Event Tokens. This value is set as `iss`
            in the claim.
          example: https://{yourOktaDomain}
        jwks_uri:
          type: string
          description: >-
            The URL of the JSON Web Key Set (JWKS) that contains the signing
            keys for validating the signatures of Security Event Tokens (SETs)
          format: uri
          example: https://{yourOktaDomain}/oauth2/v1/keys
        spec_version:
          type: string
          description: >-
            The version identifying the implementer's draft or final
            specification implemented by the transmitter
          example: 1_0-ID3
        verification_endpoint:
          type: string
          format: uri
          description: The URL of the SSF Stream verification endpoint
          example: https://{yourOktaDomain}/api/v1/ssf/stream/verification
    PublicWebauthnSiteWellKnownURI:
      description: The well-known URI content in JSON object format
      type: object
    AuthenticatorKeyEnum:
      description: A human-readable string that identifies the authenticator
      type: string
      enum:
        - custom_app
        - duo
        - external_idp
        - google_otp
        - okta_email
        - okta_password
        - okta_verify
        - onprem_mfa
        - phone_number
        - security_key
        - security_question
        - smart_card_idp
        - symantec_vip
        - webauthn
        - yubikey_token
        - tac
    CustomAppUserVerificationEnum:
      description: User verification setting
      type: string
      enum:
        - PREFERRED
        - REQUIRED
    SupportedMethods:
      description: The supported methods of an authenticator
      type: object
      properties:
        settings:
          type: object
          properties:
            keyProtection:
              $ref: '#/components/schemas/PushMethodKeyProtection'
            algorithms:
              description: The encryption algorithm for this authenticator method
              type: array
              items:
                $ref: '#/components/schemas/AuthenticatorMethodAlgorithm'
            transactionTypes:
              type: array
              description: The transaction type for this authenticator method
              items:
                $ref: '#/components/schemas/AuthenticatorMethodTransactionType'
        status:
          description: The status of the authenticator method
          $ref: '#/components/schemas/LifecycleStatus'
        type:
          type: string
          description: The type of authenticator method
          enum:
            - push
    Error:
      title: Error
      type: object
      properties:
        errorCauses:
          type: array
          items:
            $ref: '#/components/schemas/ErrorCause'
        errorCode:
          type: string
          description: An Okta code for this type of error
        errorId:
          type: string
          description: >-
            A unique identifier for this error. This can be used by Okta Support
            to help with troubleshooting.
        errorLink:
          type: string
          description: An Okta code for this type of error
        errorSummary:
          type: string
          description: >-
            A short description of what caused this error. Sometimes this
            contains dynamically-generated information about your specific
            error.
    PipelineType:
      description: The Okta authentication pipeline of the org
      type: string
      enum:
        - idx
        - v1
      x-enumDescriptions:
        idx: >-
          [Identity
          Engine](https://help.okta.com/okta_help.htm?type=oie&id=ext-get-started-oie)
        v1: '[Classic Engine](https://help.okta.com/en-us/content/index-admin.htm)'
    HrefObject:
      title: Link Object
      additionalProperties: true
      type: object
      properties:
        hints:
          $ref: '#/components/schemas/HrefHints'
          readOnly: true
        href:
          type: string
          description: Link URI
        name:
          type: string
          description: Link name
          readOnly: true
        templated:
          type: boolean
          description: >-
            Indicates whether the link object's `href` property is a URI
            template.
          readOnly: true
        type:
          type: string
          description: >-
            The media type of the link. If omitted, it is implicitly
            `application/json`.
          readOnly: true
      required:
        - href
    WellKnownSSFMetadataSpecUrn:
      type: object
      properties:
        spec_urn:
          type: string
          format: uri
          description: The URN that describes the specification of the protocol being used
          example: urn:ietf:rfc:6749
    PushMethodKeyProtection:
      description: Indicates whether you must use a hardware key store
      type: string
      enum:
        - ANY
        - HARDWARE
    AuthenticatorMethodAlgorithm:
      type: string
      enum:
        - ES256
        - RS256
    AuthenticatorMethodTransactionType:
      type: string
      enum:
        - CIBA
        - LOGIN
    LifecycleStatus:
      type: string
      enum:
        - ACTIVE
        - INACTIVE
    ErrorCause:
      type: object
      properties:
        errorSummary:
          type: string
    HrefHints:
      description: Describes allowed HTTP verbs for the `href`
      type: object
      properties:
        allow:
          type: array
          items:
            $ref: '#/components/schemas/HttpMethod'
    HttpMethod:
      type: string
      enum:
        - DELETE
        - GET
        - POST
        - PUT
  responses:
    ErrorMissingRequiredParameter400:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            MissingRequiredParameter:
              $ref: '#/components/examples/ErrorMissingRequiredParameter'
    ErrorTooManyRequests429:
      description: Too Many Requests
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            TooManyRequests:
              $ref: '#/components/examples/ErrorTooManyRequests'
    ErrorResourceNotFound404:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            ResourceNotFound:
              $ref: '#/components/examples/ErrorResourceNotFound'
    ErrorInvalidToken401:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            InvalidTokenProvided:
              $ref: '#/components/examples/ErrorInvalidTokenProvided'
    ErrorAccessDenied403:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            AccessDenied:
              $ref: '#/components/examples/ErrorAccessDenied'
  examples:
    WellKnownAppAuthenticatorConfigurationCustomApp:
      value:
        - authenticatorId: aut22f6xzargnJZYE3l7
          orgId: 00o1vhf34q20MfCFC3l7
          type: app
          key: custom_app
          name: Custom authenticator
          createdDate: '2022-10-11T08:56:45.000Z'
          lastUpdated: '2023-09-07T11:31:35.000Z'
          settings:
            userVerification: PREFERRED
          supportedMethods:
            - type: push
              status: ACTIVE
              settings:
                algorithms:
                  - RS256
                  - ES256
                keyProtection: ANY
          appAuthenticatorEnrollEndpoint: https://{yourOktaDomain}/idp/myaccount/app-authenticators
    PublicAppleAppSiteWellKnownURIResponse:
      value:
        authsrv:
          apps:
            - B7F62B65BN.com.okta.mobile
            - B7F62B65BN.com.okta.mobile.auth-service-extension
            - B7F62B65BN.com.okta.authenticator.beta
            - B7F62B65BN.com.okta.authenticator.beta.auth-service-extension
            - 7WXXBW6Z2Y.com.okta.mobile.internalrelease
            - 7WXXBW6Z2Y.com.okta.mobile.internalrelease.auth-service-extension
          key1: value1
          key2: value2
          key3:
            key3.1: value3.1
    PublicAssetLinksWellKnownURIResponse:
      value:
        - key1: value1
    WellKnownOrgMetadataResponseCustomUrlOie:
      value:
        id: 00o47wwoytgsDqEtz0g7
        _links:
          organization:
            href: https://{yourSubdomain}.okta.com
          alternate:
            href: https://{yourCustomDomain}
        pipeline: idx
    WellKnownOrgMetadataResponseClassic:
      value:
        id: 00o5rb5mt2H3d1TJd0h7
        _links:
          organization:
            href: https://{{yourOktaDomain}}
        pipeline: v1
    wellKnownSSFMetadataExample:
      summary: Well-Known SSF metadata example
      value:
        configuration_endpoint: https://{yourOktaDomain}/api/v1/ssf/stream
        delivery_methods_supported:
          - https://schemas.openid.net/secevent/risc/delivery-method/push
          - urn:ietf:rfc:8935
        issuer: https://{yourOktaDomain}
        jwks_uri: https://{yourOktaDomain}/oauth2/v1/keys
        verification_endpoint: https://{yourOktaDomain}/api/v1/ssf/stream/verification
        spec_version: 1_0-ID3
        authorization_schemes:
          - spec_urn: urn:ietf:rfc:6749
        default_subjects: ALL
    PublicWebauthnWellKnownURIResponse:
      value:
        origins:
          - https://example1.com
    ErrorMissingRequiredParameter:
      summary: Missing Required Parameter
      value:
        errorCode: E0000028
        errorSummary: The request is missing a required parameter.
        errorLink: E0000028
        errorId: sampleiCF-l7mr9XqM1NQ
        errorCauses: []
    ErrorTooManyRequests:
      summary: Too Many Requests
      value:
        errorCode: E0000047
        errorSummary: API call exceeded rate limit due to too many requests.
        errorLink: E0000047
        errorId: sampleQPivGUj_ND5v78vbYWW
        errorCauses: []
    ErrorResourceNotFound:
      summary: Resource Not Found
      value:
        errorCode: E0000007
        errorSummary: 'Not found: {0}'
        errorLink: E0000007
        errorId: sampleMlLvGUj_YD5v16vkYWY
        errorCauses: []
    ErrorInvalidTokenProvided:
      summary: Invalid Token Provided
      value:
        errorCode: E0000011
        errorSummary: Invalid token provided
        errorLink: E0000011
        errorId: sampleQPivGUj_ND5v78vbYWW
        errorCauses: []
    ErrorAccessDenied:
      summary: Access Denied
      value:
        errorCode: E0000006
        errorSummary: You do not have permission to perform the requested action
        errorLink: E0000006
        errorId: sampleNUSD_8fdkFd8fs8SDBK
        errorCauses: []
servers:
  - url: https://{yourOktaDomain}
    variables:
      yourOktaDomain:
        default: subdomain.okta.com
        description: >-
          The domain of your organization. This can be a provided subdomain of
          an official okta domain (okta.com, oktapreview.com, etc) or one of
          your configured custom domains.
